import type { Metadata } from "next";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { playfairDisplay, poppins, robotoMono } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang='en'>
        <body
          className={`${poppins.variable} ${playfairDisplay.variable} ${robotoMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
